//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryPresentacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_appointment()
        {
            this.tb_proof_of_purchase = new HashSet<tb_proof_of_purchase>();
        }
    
        public int id { get; set; }
        public System.TimeSpan hour { get; set; }
        public System.DateTime date { get; set; }
        public int id_doctor { get; set; }
        public string id_patient { get; set; }
        public int id_receptionist { get; set; }
        public Nullable<bool> state { get; set; }
    
        public virtual tb_doctor tb_doctor { get; set; }
        public virtual tb_patient tb_patient { get; set; }
        public virtual tb_receptionist tb_receptionist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_proof_of_purchase> tb_proof_of_purchase { get; set; }
    }
}
