//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryPresentacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_contrareferencia
    {
        public int id { get; set; }
        public string est_ref_name { get; set; }
        public string est_ref_dir { get; set; }
        public string est_contref_name { get; set; }
        public string est_contref_dir { get; set; }
        public string est_contref_diagnosis { get; set; }
        public string treatment { get; set; }
        public string ind_aps { get; set; }
        public System.DateTime date_contref { get; set; }
        public string id_patient { get; set; }
        public int id_doctor { get; set; }
        public int id_receptionist { get; set; }
        public Nullable<bool> state { get; set; }
    
        public virtual tb_doctor tb_doctor { get; set; }
        public virtual tb_patient tb_patient { get; set; }
        public virtual tb_receptionist tb_receptionist { get; set; }
    }
}
