//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryPresentacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_receptionist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_receptionist()
        {
            this.tb_appointment = new HashSet<tb_appointment>();
            this.tb_contrareferencia = new HashSet<tb_contrareferencia>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string a_p { get; set; }
        public string a_m { get; set; }
        public string dni { get; set; }
        public string password { get; set; }
        public Nullable<bool> state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_appointment> tb_appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_contrareferencia> tb_contrareferencia { get; set; }
    }
}
